import type { Metadata } from "next";
import { Roboto } from "next/font/google";
import "./globals.css";
import { AntdRegistry } from "@ant-design/nextjs-registry";
import { ClerkProvider } from "@clerk/nextjs";

const font = Roboto(
  { weight: ["400"], subsets: ["latin"] }
);

export const metadata: Metadata = {
  title: "Quick Mart",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <>
      <ClerkProvider>
        <html lang="en">
          <body className={font.className}>
            <AntdRegistry>
              {children}
            </AntdRegistry>
          </body>
        </html>
      </ClerkProvider>
    </>
  );
}
